//! REALITY scaffold smoke test (V0.2.1).
//!
//! Run with:
//!
//! ```text
//! cargo run -p parseh-relay --example reality_smoke --features reality
//! ```
//!
//! What this checks:
//!
//! 1. The `reality` module compiles and the public types are reachable.
//! 2. A fake [`RealityConfig`] round-trips through validation.
//! 3. Spawning the xray-core subprocess either:
//!    a. Succeeds (a real xray binary is on PATH) and the subprocess
//!    reaches `Running`, in which case we attempt a SOCKS5 dial to
//!    `127.0.0.1:8080` and report whether the handshake completed.
//!    b. Fails with [`SubprocessError::BinaryNotFound`], which is the
//!    expected outcome on any CI runner / dev machine that has not
//!    installed xray-core. We log + exit 0; the smoke test passes.
//!
//! This is **NOT** a verification that REALITY actually works on the
//! wire. That requires a real REALITY server endpoint and is V0.2.5
//! measurement work.

use anyhow::Result;
use parseh_relay::reality::{
    FallbackServer, RealityConfig, RealityRole, RealitySubprocess, RealityTransport,
    SubprocessError, SubprocessState,
};

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter("parseh_relay=debug,reality_smoke=info")
        .init();

    println!("=== parseh-relay REALITY scaffold smoke test (V0.2.1) ===");

    let cfg = RealityConfig {
        role: RealityRole::Client,
        server_name: "www.cloudflare.com".into(),
        fallback_server: FallbackServer {
            host: "www.cloudflare.com".into(),
            port: 443,
        },
        // 32 bytes of zeroes encoded base64 — fake key. Real keys are
        // generated by `xray x25519` and stored separately.
        private_key_b64: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".into(),
        local_listen: "127.0.0.1:18421".into(),
        remote: Some("203.0.113.1:443".into()),
    };

    println!("step 1: config validation");
    parseh_relay::reality::validate(&cfg).map_err(|e| anyhow::anyhow!("{e}"))?;
    println!("  OK");

    println!("step 2: subprocess spawn");
    match RealitySubprocess::spawn(&cfg).await {
        Ok(sp) => {
            println!("  OK · subprocess state = {:?}", sp.state());
            println!("       SOCKS5 endpoint  = {}", sp.socks_addr());

            // Try a SOCKS5 dial — this confirms the integration surface
            // moves bytes. It will likely fail to connect onward to a
            // real remote because our fake config has a bogus key /
            // peer; that is expected and not what we're testing.
            let arc = std::sync::Arc::new(sp);
            let transport = RealityTransport::new(arc.clone());
            println!("step 3: SOCKS5 dial through subprocess");
            match transport.dial_via_socks5("127.0.0.1:8080").await {
                Ok(_) => println!("  OK · handshake completed"),
                Err(e) => println!("  expected failure (no upstream REALITY peer): {e}"),
            }

            println!("step 4: clean shutdown");
            // Reclaim the subprocess from the Arc — Arc::try_unwrap
            // succeeds because we just dropped `transport`.
            drop(transport);
            match std::sync::Arc::try_unwrap(arc) {
                Ok(sp) => {
                    sp.stop()
                        .await
                        .map_err(|e| anyhow::anyhow!("subprocess stop: {e}"))?;
                    println!("  OK");
                }
                Err(_) => println!("  skipped (transport still held a reference)"),
            }
        }
        Err(SubprocessError::BinaryNotFound) => {
            println!("  xray-core not found in PATH; install from https://github.com/XTLS/Xray-core");
            println!("  (this is the expected outcome on CI / dev machines without xray installed)");
            println!("  smoke test PASS · integration surface compiles and reports cleanly");
            return Ok(());
        }
        Err(e) => {
            println!("  unexpected subprocess error: {e}");
            return Err(anyhow::anyhow!("{e}"));
        }
    }

    // Suppress dead-code on the listener type — V0.2.5 will use it.
    let _ = std::mem::size_of::<parseh_relay::reality::RealityListener>();
    // Same for the state enum — surfacing it here keeps the public
    // type used so future refactors don't silently drop it.
    let _ = SubprocessState::NotStarted;

    println!("smoke test PASS");
    Ok(())
}
