//! REALITY configuration model.
//!
//! Two related shapes coexist:
//!
//! 1. [`RealityConfig`] — the relay-facing, TOML-friendly config the
//!    operator writes by hand (or generates with a helper script).
//! 2. The xray-core JSON config — generated from `RealityConfig` and
//!    written to a temp file the subprocess reads. This translation
//!    lives in [`crate::reality::subprocess`].
//!
//! V0.2.1 deliberately exposes a **narrow** surface. xray-core's real
//! REALITY config has dozens of knobs (shortIds, maxTimeDiff, spider
//! parameters, etc.); we ship only the four every operator must set,
//! and let `subprocess.rs` fill defaults for the rest. Widening this
//! surface is V0.2.5+ work driven by measurement need, not speculation.

use serde::{Deserialize, Serialize};

/// REALITY role for this relay endpoint.
///
/// - `Server` — accept inbound REALITY connections; this is what a
///   bridge-leg PCN runs.
/// - `Client` — initiate outbound REALITY connections; this is what an
///   internal-leg PCN, or a Hiderun client, runs when it wants to dial
///   a bridge.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RealityRole {
    Server,
    Client,
}

/// The real HTTPS site this tunnel mimics. If the REALITY handshake
/// fails (e.g. the peer is not actually a PARSEH client and is just an
/// active probe from the censor), xray-core transparently proxies the
/// connection to this server — so the prober sees a perfectly normal
/// TLS connection to a real website.
///
/// Operator guidance: pick a site that is (a) unblocked in the target
/// jurisdiction, (b) widely used so its presence is not anomalous, and
/// (c) supports TLS 1.3 with X25519. `www.cloudflare.com`, `www.bing.com`,
/// and `www.microsoft.com` are common choices. The chosen host MUST
/// match [`RealityConfig::server_name`].
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct FallbackServer {
    pub host: String,
    pub port: u16,
}

impl Default for FallbackServer {
    fn default() -> Self {
        Self {
            host: "www.cloudflare.com".to_string(),
            port: 443,
        }
    }
}

/// Operator-facing REALITY config block. Designed to live under a
/// `[reality]` section in the relay's `relay.toml`.
///
/// **Security note.** `private_key_b64` is the long-term X25519 private
/// key for this REALITY role. If this leaks, an active adversary can
/// impersonate the bridge to any client that has the matching public
/// key. Store the file 0600 (the existing identity-store pattern) and
/// never commit a real key to version control. V0.2.5 will move this
/// into the SQLCipher-encrypted local store; today it sits in plain
/// TOML because the alternative is shipping a half-integrated KDF and
/// that's worse.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RealityConfig {
    /// `server` (accept inbound REALITY) or `client` (initiate outbound).
    pub role: RealityRole,

    /// SNI to present on the wire. MUST match `fallback_server.host`,
    /// or xray-core will refuse the config (and a censor would notice
    /// the mismatch anyway).
    pub server_name: String,

    /// The real HTTPS site this tunnel impersonates. See
    /// [`FallbackServer`] docs for selection guidance.
    pub fallback_server: FallbackServer,

    /// Base64-encoded X25519 private key (32 raw bytes → 44 chars
    /// without padding stripped, 44 with `=` padding). Generated by
    /// `xray x25519` in xray-core; PARSEH does NOT generate this key
    /// itself because key-format compatibility is one of the most
    /// fragile points across xray-core minor releases.
    pub private_key_b64: String,

    /// Loopback address the subprocess listens on for the Rust side to
    /// connect to. Always 127.0.0.1 / ::1 — never expose this port to
    /// any non-loopback interface; the traffic between the Rust process
    /// and the subprocess is plaintext by design (the wire encryption
    /// happens AFTER this hop).
    pub local_listen: String,

    /// Remote address to dial (for `RealityRole::Client`). Format:
    /// `host:port`. Ignored for `RealityRole::Server`. If `None` in
    /// client role, the subprocess will fail to spawn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub remote: Option<String>,
}

impl Default for RealityConfig {
    fn default() -> Self {
        Self {
            role: RealityRole::Client,
            server_name: "www.cloudflare.com".to_string(),
            fallback_server: FallbackServer::default(),
            // Empty by default — `validate()` rejects this so the operator
            // is forced to supply a real key.
            private_key_b64: String::new(),
            local_listen: "127.0.0.1:18421".to_string(),
            remote: None,
        }
    }
}

/// Validation errors. Distinct enum (rather than `anyhow`) so callers
/// can match on the specific failure — e.g. the smoke test wants to
/// distinguish "you forgot a key" from "you wrote a bad port".
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum ConfigError {
    #[error("server_name is empty")]
    EmptyServerName,
    #[error("private_key_b64 is empty")]
    EmptyPrivateKey,
    #[error("private_key_b64 does not look like base64 (got {0} chars)")]
    PrivateKeyNotBase64(usize),
    #[error("server_name '{server}' does not match fallback_server.host '{fallback}'")]
    SniMismatch { server: String, fallback: String },
    #[error("fallback_server.port must not be 0")]
    ZeroFallbackPort,
    #[error("fallback_server.host is empty")]
    EmptyFallbackHost,
    #[error("local_listen '{0}' is not a 127.0.0.1 / ::1 loopback address")]
    NonLoopbackLocalListen(String),
    #[error("local_listen '{0}' is not a valid host:port")]
    InvalidLocalListen(String),
    #[error("client role requires `remote = \"host:port\"` to be set")]
    ClientMissingRemote,
}

/// Run all the cheap, deterministic checks. Anything that requires an
/// actually-running xray binary (key validity vs xray's parser, real
/// network reachability of the fallback) is **out of scope here** —
/// that gets caught by [`super::subprocess::RealitySubprocess::spawn`]
/// when it tries to launch.
pub fn validate(cfg: &RealityConfig) -> Result<(), ConfigError> {
    if cfg.server_name.trim().is_empty() {
        return Err(ConfigError::EmptyServerName);
    }
    if cfg.fallback_server.host.trim().is_empty() {
        return Err(ConfigError::EmptyFallbackHost);
    }
    if cfg.fallback_server.port == 0 {
        return Err(ConfigError::ZeroFallbackPort);
    }
    if cfg.server_name != cfg.fallback_server.host {
        return Err(ConfigError::SniMismatch {
            server: cfg.server_name.clone(),
            fallback: cfg.fallback_server.host.clone(),
        });
    }
    if cfg.private_key_b64.trim().is_empty() {
        return Err(ConfigError::EmptyPrivateKey);
    }
    // Loose check: REALITY uses raw 32-byte X25519 keys → 44 base64
    // chars with padding, 43 without. We accept 43–44 ASCII chars.
    // Strict base64 round-tripping happens in the subprocess; we are
    // only catching obvious typos here.
    let pk_trim = cfg.private_key_b64.trim();
    if !(40..=64).contains(&pk_trim.len())
        || !pk_trim
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '+' || c == '/' || c == '-' || c == '_' || c == '=')
    {
        return Err(ConfigError::PrivateKeyNotBase64(pk_trim.len()));
    }
    // local_listen must parse as a SocketAddr and must be loopback.
    let parsed: std::net::SocketAddr = cfg
        .local_listen
        .parse()
        .map_err(|_| ConfigError::InvalidLocalListen(cfg.local_listen.clone()))?;
    if !parsed.ip().is_loopback() {
        return Err(ConfigError::NonLoopbackLocalListen(cfg.local_listen.clone()));
    }
    if matches!(cfg.role, RealityRole::Client) && cfg.remote.is_none() {
        return Err(ConfigError::ClientMissingRemote);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn good() -> RealityConfig {
        RealityConfig {
            role: RealityRole::Client,
            server_name: "www.cloudflare.com".into(),
            fallback_server: FallbackServer {
                host: "www.cloudflare.com".into(),
                port: 443,
            },
            // 32 bytes → 44 base64 chars. Arbitrary fake key, not used
            // for any real handshake in tests.
            private_key_b64: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=".into(),
            local_listen: "127.0.0.1:18421".into(),
            remote: Some("203.0.113.1:443".into()),
        }
    }

    #[test]
    fn valid_config_passes() {
        assert!(validate(&good()).is_ok());
    }

    #[test]
    fn empty_server_name_rejected() {
        let mut c = good();
        c.server_name.clear();
        assert_eq!(validate(&c).unwrap_err(), ConfigError::EmptyServerName);
    }

    #[test]
    fn empty_private_key_rejected() {
        let mut c = good();
        c.private_key_b64.clear();
        assert_eq!(validate(&c).unwrap_err(), ConfigError::EmptyPrivateKey);
    }

    #[test]
    fn sni_mismatch_rejected() {
        let mut c = good();
        c.server_name = "www.bing.com".into();
        assert!(matches!(
            validate(&c).unwrap_err(),
            ConfigError::SniMismatch { .. }
        ));
    }

    #[test]
    fn non_loopback_local_listen_rejected() {
        let mut c = good();
        c.local_listen = "0.0.0.0:18421".into();
        assert!(matches!(
            validate(&c).unwrap_err(),
            ConfigError::NonLoopbackLocalListen(_)
        ));
    }

    #[test]
    fn client_role_requires_remote() {
        let mut c = good();
        c.remote = None;
        assert_eq!(validate(&c).unwrap_err(), ConfigError::ClientMissingRemote);
    }
}
